### ISSUE TITLE
Can you help to see if there is a mistake or what is the situation, the failure of her now

### ISSUE THREAD

**Issue by winie-hy** [AshwinPathi/claude-api-py#20] opened 2023-08-16 03:56 UTC
![image](https://github.com/AshwinPathi/claude-api-py/assets/59427119/0ceecd01-5ae8-45ab-922e-accd7b6c177a)
Can you help to see if there is a mistake or what is the situation, the failure of her now @AshwinPathi

**Comment by AshwinPathi** [comment] 2023-08-16 04:04
Duplicate of https://github.com/AshwinPathi/claude-api-py/issues/19

**Comment by winie-hy** [comment] 2023-08-16 04:05
like this 
![image](https://github.com/AshwinPathi/claude-api-py/assets/59427119/5508bd7f-1b96-4ff5-9a59-84f7f2b9ca83)

**Comment by AshwinPathi** [comment] 2023-08-16 04:07
Yes, this is the same issue. Note the `SSE POST Failed with error: HTTP Error 403: Forbidden`. 

Multiple other APIs have this issue now, I expect its some security change on Anthropic's end.

**Closed** 2023-08-16 06:03 UTC
